name: big_fun
description: Big fun — demo app with OTP, voice rooms, gifting (scaffold)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.20.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.9.0
  provider: ^6.0.5
  # For voice chat scaffold (you can replace with agora or WebRTC packages)
  # agora_rtc_engine: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
